### ISSUE TITLE
how do i configure the !reboot-vm command?

### ISSUE THREAD

**Issue by morg-mov** [John-Jelatis/VMBot-for-Discord#1]
I'm running a daemonized instance of QEMU-KVM with windows 10 on it and I want to be able to reboot the VM with the command. However, it doesn't work. May I know how to configure it?

**Comment by John-Jelatis** [comment]
Hello!

The `!reboot-vm` will run whatever command you've specified in the "reboot" parameter (in the same level of the JSON as the name and such, see the example below). 

```json
{
    "name": "Windows ME",
    "id": "winme",
    "reboot": "killall qemu-system-i386",
    "hwInf": {
        "cpu": "i386",
        "ram": 96,
        "hda": 2048,
        "other": "Windows ME is the greatest OS that Microsoft has produced yet!"
    },
    "ip": "192.168.1.10", "port": 5901
}
```

I realize that I've yet to update the readme with everything that's been added since the initial commit - for that I am sorry.

Note that the `reboot` command will simply be executed by your host's default shell (i.e. bash) and with whatever permissions you launch the bot, and (at the moment) the bot does not have the functionality to automatically start the bot back up.

As an aside, it might make sense to run your qemu instance in such a way that it will automatically boot back up in the event that it does get killed (if you aren't already):
```sh
while true; do
  qemu-system-i386 -ram 96M -hda hda.img -vnc :1;
done
```

**Comment by morg-mov** [comment]
Thanks! I think I'll just set it to kill it then run it again like this:
`killall qemu-system-x86_64 && qemu-system-x86_64 -ram 2G -vnc :1`
Thanks for the help!
